services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  web:

    image: tokenopt:dev
    build:
      context: .
      args:
        APP_ENV: dev
    working_dir: /app/tokenopt_site
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      TOKENOPT_ENABLE_GPU: "0"
      DJANGO_SETTINGS_MODULE: tokenopt_site.settings
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      PYTHONPATH: /app/tokenopt_generator:/app/tokenopt_site
    depends_on:
      - redis
    volumes:
      - ./tokenopt_site:/app/tokenopt_site
      - ./tokenopt_generator:/app/tokenopt_generator

  worker:
    image: tokenopt:dev
    working_dir: /app/tokenopt_site
    command: celery -A tokenopt_site worker -l info
    environment:
      TOKENOPT_ENABLE_GPU: "0"
      DJANGO_SETTINGS_MODULE: tokenopt_site.settings
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0
      PYTHONPATH: /app/tokenopt_generator:/app/tokenopt_site
    depends_on:
      - redis
    volumes:
      - ./tokenopt_site:/app/tokenopt_site
      - ./tokenopt_generator:/app/tokenopt_generator
