services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  web:
    build: .
    working_dir: /app/tokenopt_site
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      DJANGO_SETTINGS_MODULE: tokenopt_site.settings

      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0

      # coerente col Dockerfile
      PYTHONPATH: /app/tokenopt_generator:/app/tokenopt_site
    depends_on:
      - redis
    volumes:
      - ./tokenopt_site:/app/tokenopt_site
      - ./tokenopt_generator:/app/tokenopt_generator

  worker:
    build: .
    working_dir: /app/tokenopt_site
    # IMPORTANTE: qui devi mettere il nome app Celery corretto (vedi nota sotto)
    command: celery -A tokenopt_site worker -l info
    environment:
      DJANGO_SETTINGS_MODULE: tokenopt_site.settings

      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/0

      PYTHONPATH: /app/tokenopt_generator:/app/tokenopt_site
    depends_on:
      - redis
    volumes:
      - ./tokenopt_site:/app/tokenopt_site
      - ./tokenopt_generator:/app/tokenopt_generator
